"""Initial Migration

Revision ID: 5957031d2672
Revises: fcd3a26d6d80
Create Date: 2019-11-29 17:42:02.099027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5957031d2672'
down_revision = 'fcd3a26d6d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###
