"""Initial Migration

Revision ID: 7aa239b7f153
Revises: e005ff8d58d1
Create Date: 2019-12-02 16:11:34.911810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa239b7f153'
down_revision = 'e005ff8d58d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('Blog_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'Blog', ['Blog_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'users', ['user_id'], ['id'])
    op.drop_column('comment', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'user_id')
    op.drop_column('comment', 'Blog_id')
    # ### end Alembic commands ###
