"""Initial Migration

Revision ID: e005ff8d58d1
Revises: 45d95b4e7f36
Create Date: 2019-12-02 16:02:36.071051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e005ff8d58d1'
down_revision = '45d95b4e7f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Blog', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Blog', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Blog', type_='foreignkey')
    op.drop_column('Blog', 'user_id')
    op.drop_table('comment')
    # ### end Alembic commands ###
